// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef main_h
#define main_h
#include <FL/Fl.H>
#include <FL/Fl_File_Chooser.H>
#include <FL/Fl_Double_Window.H>
#include "Gl_Window.h"
extern Gl_Window *glWindow;
#include <FL/Fl_Button.H>
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Input.H>
#endif
